name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: fjuniorr/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=fjuniorr/${{ github.event.repository.name }}:latest
        cache-to: type=inline
    - name: ETL pipeline
      env: 
        GMAILR_KEY: ${{ secrets.GMAILR_KEY }}
      run: docker run -e GMAILR_KEY=$GMAILR_KEY --rm --mount type=bind,source=${PWD},target=/project fjuniorr/${{ github.event.repository.name }} make all
    - name: Publish data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make publish

    - name: Trigger repository_dispatch in splor-mg/dados-armazem-siafi-2024
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/splor-mg/dados-armazem-siafi-2024/dispatches \
          -d '{"event_type":"trigger-workflow"}'

    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/workflow-failure.md
